---
name: "Build and Deploy"
on:
  push:
    paths:
      - "backend/express-prisma/**"
  workflow_dispatch: 
jobs:
  build:
    name: "Build container image and push to ECR repository"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-northeast-1"

      - name: "Login to Amazon ECR"
        id: "login-ecr"
        uses: aws-actions/amazon-ecr-login@v2

      - name: "Build, tag, and push docker image to Amazon ECR"
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: todolist/backend/express-prisma
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f backend/express-prisma/docker/Dockerfile .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          
# todo: 下記
#   - main ブランチのマージ時にトリガされる、ECS タスク定義のイメージ更新とサービス最新化 の処理
